# Generated by Django 4.2.4 on 2023-09-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_remove_wallet_holders'),
        ('coins', '0002_alter_coin_name_alter_coin_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.wallet'),
        ),
    ]
