# Generated by Django 4.2.4 on 2023-09-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_remove_wallet_holders'),
        ('coins', '0003_coin_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='holder',
        ),
        migrations.AddField(
            model_name='coin',
            name='holder',
            field=models.ManyToManyField(blank=True, null=True, to='wallets.wallet'),
        ),
    ]
