# Generated by Django 4.2.4 on 2023-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_remove_wallet_holders'),
        ('coins', '0004_remove_coin_holder_coin_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='holder',
            field=models.ManyToManyField(blank=True, to='wallets.wallet'),
        ),
    ]
