# Generated by Django 4.2.4 on 2023-09-05 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_alter_coin_holder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='holder',
            new_name='holders',
        ),
        migrations.AddField(
            model_name='coin',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=2000, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
