# Generated by Django 4.2.5 on 2023-09-06 17:42

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_alter_wallet_main_wallet'),
        ('coins', '0007_coin_market_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_buy_price', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), default=list, size=None)),
                ('amount_of_coin', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, default=list, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='market_cap',
        ),
        migrations.AddField(
            model_name='coin',
            name='stocks_left',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), default=list, size=None),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount_of_coin', models.DecimalField(decimal_places=5, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet')),
            ],
        ),
    ]
