# Generated by Django 4.2.5 on 2023-09-06 17:43

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_coinholder_remove_coin_market_cap_coin_stocks_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='market_cap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), default=list, size=None),
        ),
    ]
