# Generated by Django 4.2.5 on 2023-09-07 10:00

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0009_coin_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='coin',
            name='stocks_left',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), blank=True, default=list, null=True, size=None),
        ),
    ]
