# Generated by Django 4.2.5 on 2023-09-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0010_alter_coin_market_cap_alter_coin_stocks_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.coin'),
        ),
        migrations.AddField(
            model_name='coinholder',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.coin'),
        ),
    ]
