# Generated by Django 4.2.5 on 2023-09-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_rename_wallet_buy_buy_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='buy_wallet',
            new_name='wallet',
        ),
    ]
