# Generated by Django 4.2.5 on 2023-09-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_alter_wallet_main_wallet'),
        ('coins', '0015_rename_buy_wallet_buy_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinholder',
            name='holder_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.wallet'),
        ),
    ]
