# Generated by Django 4.2.5 on 2023-09-08 15:11

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0021_rename_avg_buy_price_coinholder__avg_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinholder',
            name='_avg_buy_price',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='coinholder',
            name='amount_of_coin',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]), default=list, size=None),
        ),
    ]
