# Generated by Django 4.2.5 on 2023-09-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0022_alter_coinholder__avg_buy_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinholder',
            old_name='amount_of_coin',
            new_name='_amount_of_coin',
        ),
    ]
