# Generated by Django 4.2.5 on 2023-09-11 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_alter_wallet_main_wallet'),
        ('coins', '0024_alter_buy_amount_of_coin_alter_buy_total_price_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='_market_cap',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='_stocks_left',
        ),
        migrations.RemoveField(
            model_name='coinholder',
            name='_amount_of_coin',
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(decimal_places=3, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='coinholder',
            name='amount_of_coin',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coinholder',
            name='holder_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.wallet'),
        ),
    ]
