# Generated by Django 4.2.5 on 2023-09-11 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0025_remove_coin__market_cap_remove_coin__stocks_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='stocks_left',
            field=models.DecimalField(decimal_places=3, default=1000, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
