# Generated by Django 4.2.5 on 2023-09-11 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0026_coin_stocks_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
