# Generated by Django 4.2.5 on 2023-09-12 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0027_alter_coin_market_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='stocks_left',
        ),
        migrations.AddField(
            model_name='coin',
            name='_stocks_left',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
