# Generated by Django 4.2.4 on 2023-08-29 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('wallet_id', models.CharField(max_length=6, unique=True)),
                ('user_experience', models.IntegerField(choices=[('FRESH', 'Fresh'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], max_length=12)),
                ('yang', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
