# Generated by Django 4.2.4 on 2023-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user_experience',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], max_length=12),
        ),
    ]
