# Generated by Django 4.2.4 on 2023-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_user_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='username',
            new_name='wallet_name',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_experience',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='FRESH', max_length=12),
        ),
    ]
