# Generated by Django 4.2.4 on 2023-08-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_rename_username_wallet_wallet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
