# Generated by Django 4.2.4 on 2023-08-31 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_remove_wallet_yang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='wallet_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='wallet',
            name='yang',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
