# Generated by Django 4.2.4 on 2023-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_rename_wallet_name_wallet_name_wallet_yang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
