# Generated by Django 4.2.4 on 2023-09-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_wallet_holders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='holders',
        ),
    ]
