# Generated by Django 4.2.4 on 2023-09-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_wallet_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
    ]
