# Generated by Django 4.2.4 on 2023-09-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_mainwallet_wallet_main_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='main_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.mainwallet'),
        ),
    ]
